[package]
name = "voom"
version = "0.1.0"
authors = ["Adam Birtles <adam@adambirtles.com>"]
edition = "2018"

[lib]
name = "voom"
path = "src/lib/lib.rs"

[[bin]]
name = "voom"
path = "src/vm/main.rs"

[dependencies]
